name: Bug Report
description: Report a bug or other issue

title: "[Bug]: "

labels:
    - bug

body:
    -   type: textarea
        id: description
        attributes:
            label: Issue description
            description: |
                Be as specific and detailed as possible to help us triaging your issue. Screenshots and/or animations can be very useful in helping to understand the issue you're facing.

                Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
                Tip: You can use https://www.screentogif.com to record animations and videos.
        validations:
            required: true

    -   type: markdown
        attributes:
            value: |
                ❤️ The Dragon Code? Please consider supporting our collective on [Boosty](https://boosty.to/dragon-code).
